config/routes.rb
Rails.application.routes.draw do
  root 'image/register#index'

  namespace :image do
    post 'register' => 'register#register'
    post 'next'     => 'register#next'
    get  'reset'    => 'register#reset'
    get  'download' => 'register#download'
    delete 'delete' => 'register#delete'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/text_block.rb
class TextBlock < ApplicationRecord
  validates :text, :x1, :x2, :y1, :y2, :image_id, presence: true

  def self.view_css(image_id)
    texts = self.where(image_id: image_id)
    texts.map do |t|
      {
        x: t.x1,
        y: t.y1,
        width:  t.x2 - t.x1,
        height: t.y2 - t.y1
      }
    end
  end
end

app/models/tmp_image.rb
class TmpImage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/image/register_controller.rb
class Image::RegisterController < ApplicationController

  # *** トップページ ***
  def index
    tmp = TmpImage.first
    @image = tmp[:filename]
    @blocks = TextBlock.view_css(tmp[:image_id])
  end


  # *** ラベル登録用のメソッド ***
  def register
    pos = params[:pos]
    text = TextBlock.create(
      image_id: TmpImage.first[:image_id],
      text: pos[:text],
      x1: pos[:pos1_x1],  y1: pos[:pos1_y1],
      x2: pos[:pos2_x2],  y2: pos[:pos2_y2]
    )
    redirect_to root_path
  end


  # *** 前の操作を取り消すメソッド ***
  def delete
    TextBlock.last.delete
    redirect_to root_path
  end


  # *** 次の画像に移動するメソッド ***
  def next
    # 現状の画像を完了に
    tmp = TmpImage.first
    image = Image.find_by(filename: tmp[:filename])
    image.update(is_complete: true)
    # 新しい画像に切り替える
    files = Dir::entries("app/assets/images/")
    files.each do |file|
      next unless %w(.jpg .png .jpeg).include?(File.extname(file))
      # ファイル名が既に書き込まれていないか確認
      db_files = Image.where(filename: file)
      if db_files.empty?
        image = Image.create(filename: file)
        TmpImage.first.update(filename: file, image_id: image.id)
        break
      end
    end
    # トップページへ遷移
    redirect_to root_path
  end


  # *** ダウンロードページ ***
  def download
    respond_to do |format|
      format.html
      format.csv do
        filename = 'recognition_result'
        headers['Content-Disposition'] = "attachment; filename=\"#{filename}.csv\""
      end
    end
  end


  # *** リセット（初期化）用のページ ***
  def reset
    # データベースの中身を削除する
    Image.delete_all
    TmpImage.delete_all
    TextBlock.delete_all
    # 最初の画像を指定する ※ サンプル画像以外の場合はこちらを書き換え
    image = Image.create(filename:"image_sample_01.png")
    TmpImage.create(filename:image[:filename], image_id: image.id)
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image/register_helper.rb
module Image::RegisterHelper
end

app/views/image/register/download.html.slim
div.container
  h1 ダウンロードページ
  
  = link_to 'csv download', image_download_path(format: :csv), class: "btn btn-primary"

app/views/image/register/index.html.slim
div.top-title
  div.left-button
    = link_to "前の登録を取り消し", image_delete_path, method: :delete, data: {confirm: "取り消しますか？"}, class: "btn btn-danger"
  div.right-button align="right"
    = link_to "次の画像へ", image_next_path, method: :post, class: "btn btn-warning"

div.float2
  div#main-image
    = image_tag @image, id:"image"
    div.child id="text-pos"
    - @blocks.each do |blk|
      div.child style="top: #{blk[:y]}px; left:#{blk[:x]}px; width:#{blk[:width]}px; height:#{blk[:height]}px;"
    
div.float2
  div.form
    = form_for(:pos, url: image_register_path, method: :post) do |f|
      div.form-group
        = f.label :pos1, "１．左上の座標"
      div.form-group
        div.form-inline
          = f.label :pos1, "x :", style: "margin-right:10px;"
          = f.number_field :pos1_x1, id: 'x1', class: "form-control", style: "width:100px; margin-right:30px;"
          = f.label :pos1, "y :", style: "margin-right:10px;"
          = f.number_field :pos1_y1, id: 'y1', class: "form-control", style: "width:100px; margin-right:30px;"
      div.form-group
        = f.label :pos2, "２．右下の座標"
      div.form-group
        div.form-inline
          = f.label :pos2, "x :", style: "margin-right:10px;"
          = f.number_field :pos2_x2, id: 'x2', class: "form-control", style: "width:100px; margin-right:30px;"
          = f.label :pos2, "y :", style: "margin-right:10px;"
          = f.number_field :pos2_y2, id: 'y2', class: "form-control", style: "width:100px; margin-right:30px;"
      div.form-group
        = f.label :text, "３．テキスト"
        = f.text_area :text, class:"form-control", style:"height: 200px;"
      div.form-group
        = f.submit "登録", class:"btn btn-primary"
  
    div
      = link_to "リセット", root_path

javascript:

  count = 1  // ボタンで使うカウンター

  document.getElementById( "main-image" ).addEventListener( "click", function( e ) {
  	// マウス位置を取得する
  	var mouseX = e.pageX ;	// X座標
  	var mouseY = e.pageY ;	// Y座標
    
    // 要素の位置を取得
    var element = document.getElementById( "main-image" ) ;
    var rect = element.getBoundingClientRect();
    
    // 要素の位置座標を計算
    var positionX = rect.left + window.pageXOffset ;	// 要素のX座標
    var positionY = rect.top  + window.pageYOffset ;	// 要素のY座標
    
    // 要素の左上からの距離を計算
    var X = mouseX - positionX;
    var Y = mouseY - positionY;
    
    // formの要素のvalueに代入
    $('#x'+count).val(X);
    $('#y'+count).val(Y);
    
    console.log([count, X, Y]);
    
    // count up
    count += 1
    
    if(count > 1) {
       var element = document.getElementById("text-pos"); 
       var x1 = $('#x1').val();
       var y1 = $('#y1').val();
       var x2 = $('#x2').val();
       var y2 = $('#y2').val();
       var width  = x2 - x1;
       var height = y2 - y1;
       element.style.width  = width  + 'px'; 
       element.style.height = height + 'px'; 
       element.style.top  = y1 + 'px'; 
       element.style.left = x1 + 'px'; 
    }
  } ) ;

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TegakiRecog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>